/*
 * generated by Xtext
 */
package org.modaptix.xtext.expressions.ui.contentassist

import org.modaptix.xtext.expressions.ui.contentassist.AbstractArithmeticExpressionProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ArithmeticExpressionProposalProvider extends AbstractArithmeticExpressionProposalProvider {
}
