/*
* generated by Xtext
*/
package org.modaptix.xtext.expressions;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ArithmeticExpressionStandaloneSetup extends ArithmeticExpressionStandaloneSetupGenerated{

	public static void doSetup() {
		new ArithmeticExpressionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

