/*
 * generated by Xtext
 */
package org.modaptix.xtext.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArithmeticExpressionUiModule extends org.modaptix.xtext.expressions.ui.AbstractArithmeticExpressionUiModule {
	public ArithmeticExpressionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
