/*
 * generated by Xtext
 */
package org.modaptix.xtext.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArithmeticExpressionUiModule extends
		org.modaptix.xtext.expressions.ui.AbstractArithmeticExpressionUiModule
{
	public ArithmeticExpressionUiModule(AbstractUIPlugin plugin)
	{
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration()
	{
		return ArithmeticExpressionHighlightingConfiguration.class;
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper()
	{
		return ArithmeticExpressionAntlrTokenToAttributeIdMapper.class ;
	}
}
